site_name: Anand Gupta
site_url: https://anandgupta1202.github.io/
nav:
  - Home: index.md
  - Blog:
      - Blog Homepage: blog/index.md
plugins:
  - blog:
      enabled: true
      blog_dir: blog
      blog_toc: true
      post_dir: "{blog}/posts"
      post_date_format: medium
      post_url_format: "{date}/{slug}"
      post_url_max_categories: 1
      post_slugify_separator: "-"
      post_excerpt_max_authors: 2
      post_excerpt_max_categories: 5
      post_excerpt_separator: <!-- more -->
      post_readtime: false
      archive: true
      archive_name: Archive
      archive_toc: false
      categories: true
      categories_name: Categories
      categories_slugify_separator: "-"
      categories_toc: false
      authors: true
      authors_file: "{blog}/.authors.yml"
      draft: false
  - search:
      enabled: true
      lang: en
  - social:
      cards: true
      cards_dir: socialcards
theme:
  name: material
  features:
    - announce.dismiss
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-3 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-6
        name: Switch to light mode
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anandgupta1202
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AnandGupta1202
  analytics:
    provider: google
    property: G-BE3TCP0T2D
extra_css:
  - stylesheets/extra.css
watch:
  - includes